### ISSUE TITLE
A question about the program 'generate_s1_random_Graph.py'

### ISSUE THREAD

**Issue by dange-academic** [VinceThi/low-rank-hypothesis-complex-systems#1]
Dear prof. Vincent:
Recently, I'm lucky to read your project "Low-Rank-Hypothesis-Complex-Systems" uploaded on Github repository. I have some knowledge of S1 random graph models and had some questions when I read your program 'generate_s1_random_graph.py'. The code line:
`thetas = uniform.rvs(size=N)`
According to the paper by Serrano et al[Serrano M Á, Krioukov D, Boguná M. Self-similarity of complex networks and hidden metric spaces[J]. Physical review letters, 2008, 100(7): 078701.], theta belongs to [0, 2*pi). So I want to know the difference between `thetas = uniform.rvs(size=N)` and `thetas = 2*np.pi*uniform.rvs(size=N)`. In my tests, I found that the network generated by the former has a higher density of edges.
![微信截图_20221004215710](https://user-images.githubusercontent.com/110841103/193843047-a5c0e42b-b33b-4876-a98a-582e52e6c7c7.png)

best,
Dan

**Comment by VinceThi** [comment]
Dear Dan, 

Thank you for your interest in our project and for reporting the issue, I have corrected (and updated) the code by adding the factor 2*np.pi as you have pointed out. The figure S3 and the Table SIV in the Supplementary information of the actual arXiv version of the paper will also be updated accordingly in the future versions (altough it doesn't change the conclusion of the paper).

If you find anything else, let us know !

Thanks again and best regards,

Vincent
